//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from AnalizadorLexico.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Proyecto_1.AnalizadorLexico {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="AnalizadorLexicoParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IAnalizadorLexicoVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorLexicoParser.inicio"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInicio([NotNull] AnalizadorLexicoParser.InicioContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorLexicoParser.listaInstr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListaInstr([NotNull] AnalizadorLexicoParser.ListaInstrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorLexicoParser.instruccion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruccion([NotNull] AnalizadorLexicoParser.InstruccionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorLexicoParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrint([NotNull] AnalizadorLexicoParser.PrintContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>declaracionVar</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.declaracionVariable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracionVar([NotNull] AnalizadorLexicoParser.DeclaracionVarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>declaracionSliceVacio</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.declaracionSlice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracionSliceVacio([NotNull] AnalizadorLexicoParser.DeclaracionSliceVacioContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>declaracionSliceLleno</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.declaracionSlice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracionSliceLleno([NotNull] AnalizadorLexicoParser.DeclaracionSliceLlenoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>declaracionMatrizLleno</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.declaracionMatriz"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracionMatrizLleno([NotNull] AnalizadorLexicoParser.DeclaracionMatrizLlenoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorLexicoParser.listaFilas"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListaFilas([NotNull] AnalizadorLexicoParser.ListaFilasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorLexicoParser.fila"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFila([NotNull] AnalizadorLexicoParser.FilaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>asignacionVar</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignacionVar([NotNull] AnalizadorLexicoParser.AsignacionVarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>asignacionIncremento</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignacionIncremento([NotNull] AnalizadorLexicoParser.AsignacionIncrementoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>asignacionSlice</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignacionSlice([NotNull] AnalizadorLexicoParser.AsignacionSliceContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>append</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppend([NotNull] AnalizadorLexicoParser.AppendContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sliceUpdate</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSliceUpdate([NotNull] AnalizadorLexicoParser.SliceUpdateContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>incrementoDecremento</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncrementoDecremento([NotNull] AnalizadorLexicoParser.IncrementoDecrementoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>matrizUpdate</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatrizUpdate([NotNull] AnalizadorLexicoParser.MatrizUpdateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorLexicoParser.tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTipo([NotNull] AnalizadorLexicoParser.TipoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorLexicoParser.instruccion_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruccion_if([NotNull] AnalizadorLexicoParser.Instruccion_ifContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorLexicoParser.instruccion_ifelse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruccion_ifelse([NotNull] AnalizadorLexicoParser.Instruccion_ifelseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorLexicoParser.instruccion_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruccion_else([NotNull] AnalizadorLexicoParser.Instruccion_elseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorLexicoParser.instruccion_switch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruccion_switch([NotNull] AnalizadorLexicoParser.Instruccion_switchContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorLexicoParser.lista_case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLista_case([NotNull] AnalizadorLexicoParser.Lista_caseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorLexicoParser.instruccion_case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruccion_case([NotNull] AnalizadorLexicoParser.Instruccion_caseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorLexicoParser.instruccion_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruccion_default([NotNull] AnalizadorLexicoParser.Instruccion_defaultContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>forNormal</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.instruccion_for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForNormal([NotNull] AnalizadorLexicoParser.ForNormalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>forIncremento</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.instruccion_for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForIncremento([NotNull] AnalizadorLexicoParser.ForIncrementoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>forRange</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.instruccion_for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForRange([NotNull] AnalizadorLexicoParser.ForRangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorLexicoParser.instruccion_funcion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruccion_funcion([NotNull] AnalizadorLexicoParser.Instruccion_funcionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorLexicoParser.llamada_funcion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLlamada_funcion([NotNull] AnalizadorLexicoParser.Llamada_funcionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorLexicoParser.lista_parametros"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLista_parametros([NotNull] AnalizadorLexicoParser.Lista_parametrosContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorLexicoParser.breakInstr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakInstr([NotNull] AnalizadorLexicoParser.BreakInstrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorLexicoParser.continueInstr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinueInstr([NotNull] AnalizadorLexicoParser.ContinueInstrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorLexicoParser.returnInstr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnInstr([NotNull] AnalizadorLexicoParser.ReturnInstrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>booleanExpresion</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanExpresion([NotNull] AnalizadorLexicoParser.BooleanExpresionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>strconvParseFloat</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStrconvParseFloat([NotNull] AnalizadorLexicoParser.StrconvParseFloatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TypeOf</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeOf([NotNull] AnalizadorLexicoParser.TypeOfContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>operadorLogico</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperadorLogico([NotNull] AnalizadorLexicoParser.OperadorLogicoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expreParentesis</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpreParentesis([NotNull] AnalizadorLexicoParser.ExpreParentesisContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>idExpresion</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdExpresion([NotNull] AnalizadorLexicoParser.IdExpresionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sliceAccess</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSliceAccess([NotNull] AnalizadorLexicoParser.SliceAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ejecutarFunciones</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEjecutarFunciones([NotNull] AnalizadorLexicoParser.EjecutarFuncionesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>strconvAtoi</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStrconvAtoi([NotNull] AnalizadorLexicoParser.StrconvAtoiContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>matrizAccess</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatrizAccess([NotNull] AnalizadorLexicoParser.MatrizAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stringsJoin</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringsJoin([NotNull] AnalizadorLexicoParser.StringsJoinContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>operadorNegacion</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperadorNegacion([NotNull] AnalizadorLexicoParser.OperadorNegacionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>caracterExpresion</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaracterExpresion([NotNull] AnalizadorLexicoParser.CaracterExpresionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>decimalExpresion</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecimalExpresion([NotNull] AnalizadorLexicoParser.DecimalExpresionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nilExpresion</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNilExpresion([NotNull] AnalizadorLexicoParser.NilExpresionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sliceIndex</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSliceIndex([NotNull] AnalizadorLexicoParser.SliceIndexContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>cadenaExpresion</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCadenaExpresion([NotNull] AnalizadorLexicoParser.CadenaExpresionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>len</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLen([NotNull] AnalizadorLexicoParser.LenContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>multiplicacionYdivision</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicacionYdivision([NotNull] AnalizadorLexicoParser.MultiplicacionYdivisionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>intExpresion</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntExpresion([NotNull] AnalizadorLexicoParser.IntExpresionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>operadorRelacional</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperadorRelacional([NotNull] AnalizadorLexicoParser.OperadorRelacionalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>operadorNegativo</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperadorNegativo([NotNull] AnalizadorLexicoParser.OperadorNegativoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sumaYresta</c>
	/// labeled alternative in <see cref="AnalizadorLexicoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSumaYresta([NotNull] AnalizadorLexicoParser.SumaYrestaContext context);
}
} // namespace Proyecto_1.AnalizadorLexico
